### ISSUE TITLE
Uncaught (in promise) Error: Cannot call a class as a function(…)

### ISSUE THREAD

**Issue by scaljeri** [guybedford/jspm-react-component-demo#1]
When I build this demo as described in the README with jspm version 0.17-beta.6 I get the following error in the browser console

```
Uncaught (in promise) Error: Cannot call a class as a function(…)
addToError @     system.src.js:43
linkSetFailed @ system.src.js:636(anonymous function) @     system.src.js:571
doDynamicExecute @ system.src.js:719link @ system.src.js:912  
...
```

Also, but probably not related, is it possible to run the build command, something like this

```
$> jspm build test.js app.js --skip-source-maps --minify
 Creating the single-file build for test.js...

err  Error on translate for test.js at file:///home/dev/workspace/tmp/jspm-react-component-demo/test.js
ReferenceError: [BABEL] file:///home/dev/workspace/tmp/jspm-react-component-demo/test.js: Unknown option: /home/dev/workspace/.babelrc.optional**
```

Now I get a babel error. Any help would be appreciated!

**Comment by guybedford** [comment]
Thanks, I've updated the hotreloader project to remove this message. Much appreciated for letting me know about this.

**Comment by scaljeri** [comment]
Thanks a lot for the quick fix, it works great. I've fixed the babel error, there was a .babelrc file somewhere in a parent directory
