### ISSUE TITLE
Add a testing framework 

### ISSUE THREAD

**Issue by rafi-cengage** [guybedford/jspm-react-component-demo#2]
Is it possible we can add a testing framework. I understand that would be more than just JSPM but that's the part I am struggling with right now. I am trying to get Karma to play nice with JSPM with no luck.

**Comment by guybedford** [comment]
Did you try Karma SystemJS?

**Comment by rafi-cengage** [comment]
Yes I did. I have got everything working except dependency working, like using require/import. It says require is undefined. Have you fiddled with this by any chanc?

Now it seems to recognize require but it can't find dependencies... For example importing react, it looks in the root of the project rather than looking for the package using the config file.

**Comment by rafiwardak2003** [comment]
Please close this... I started a fork for JSPM-Karma and got it working for this beta version.
