### ISSUE TITLE
Demo breaks with plugin-babel v0.0.3

### ISSUE THREAD

**Issue by miguelcaires** [guybedford/jspm-react-component-demo#3]
Hi Guy. 

I was going through the jspm 0.17 beta Guide.

After doing the steps in **1. Creating a project**, I got the following error when firing up the server:

```
Uncaught (in promise) SyntaxError: http://localhost:8000/jspm_packages/npm/systemjs-plugin-babel@0.0.3/babel-helpers/createClass.js: Unexpected token (17:2)(…)
```

in systemjs-label-browser.js.

Then tried to checkout the demo repo, ran the server and it's all fine. 
I upgraded the demo plugin-babel to 0.0.3, which is the version you'll get when you do a fresh jspm init, and was able to replicate the error above.

Just thought I'd give you a heads up.

Thanks!

**Comment by guybedford** [comment]
Thanks so much for letting me know. I've updated the plugin in the demo now.
