### ISSUE TITLE
Build command fails out of the box

### ISSUE THREAD

**Issue by MeoMix** [guybedford/jspm-react-component-demo#4]
Hey,

I'm encountering this error:

> err  Build exclusion "C:\Users\Meo\Desktop\jspm-react-component-demo-master\src/component.js" needs an external reference.
>       Either output to a module format like --format amd or map the external module to an environment global via --global-deps "{'C:\Users\Meo\Desktop\jspm-react-component-demo-master\src/component.js': 'C:\Users\Meo\Desktop\jspmReactComponentDemoMaster\src/component.js'}"

All I've done is downloaded the .zip of this repo, installed jspm@beta, and ran:

`jspm build jspm-react-component - react dist/jspm-react-component.js --format umd --global-name jspmReactComponent --global-deps "{'react':'React'}" --skip-source-maps`

I omitted the slash + linebreak which was seen in the docs, but I don't believe this is the issue.

Windows 10, latest JSPM beta.

**Comment by guybedford** [comment]
The path `C:\Users\Meo\Desktop\jspm-react-component-demo-master\src/component.js` looks wrong here with the `/`. Perhaps this is a windows bug.

**Comment by MeoMix** [comment]
I agree that it looks incorrect.

The value `src/` is being pulled in via `paths` in `jspm.browser.js`.

If I change the code such that `test.js` imports `src/component.js` rather than `jspm-react-component` then things start to work well again.

I'd assume some sort of path normalization is being applied too early and then a path substitution is being made, or just an incorrect assumption that all paths, both in the browser and in Node, use forward slashes.

I'm actually working out some of my own issues w.r.t windows right now. I was trying to avoid importing `path`, but it turns out resolving relative paths is trickier than I thought due to the backwards/forwards slash issue.

**Comment by guybedford** [comment]
Fixed in https://github.com/jspm/jspm-cli/commit/374c89c68e9492e99ee8579f4baa37cca4e05d6d.
