### ISSUE TITLE
breaks after `jspm update`

### ISSUE THREAD

**Issue by aeosynth** [guybedford/jspm-react-component-demo#6]
i followed the beta guide up to installing jsx, which didn't work. tried out this repo, it works, until i run `jspm update`:

```
system.src.js:123 Uncaught (in promise) Error: Error: Module ./definitions/init not declared as a dependency of http://127.0.0.1:8000/jspm_packages/npm/babel-types@6.8.1/lib/index.js(…)
```

if i remove the jsx plugin from `jspm.config.js` and remove jsx syntax from the files, it works again

**Comment by guybedford** [comment]
I think this was a temporary regression in jspm? The update seem to work for me now.
