### ISSUE TITLE
babel plugin for react jsx

### ISSUE THREAD

**Issue by sahiljain112** [guybedford/jspm-react-component-demo#7]
Hey @guybedford. I was reading the docs for jspm@beta. There was a link to this repository there.
The docs don't have an option for babel transformation for jsx syntax. As a beginner, it took me quite some time to go through the package.json and config file of this repository where I came across this code snippet 
`"babelOptions": {
            "plugins": [
              "babel-plugin-transform-react-jsx"
            ]
          }`

It helped me solved the problem. But mentioning this would greatly save time.
I also tried using the babel-preset-react in my .babelrc file but that didn't work. Can you tell me why?

**Comment by guybedford** [comment]
Thanks for posting, it's great to know where the gaps are for beginners. This is described in the section at http://jspm.io/0.17-beta-guide/installing-the-jsx-babel-plugin.html.

**Comment by sahiljain112** [comment]
I started with the project setup right after the first page so I didn't come across that page.
Thanks a lot :)
